name: Run Tests in my project every push on GitHub

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    generate:
    cmds:
      # Generate database bindings and data model types.
      - npm i @prisma/client
      - npx prisma generate
    steps:
    - uses: actions/checkout@v1
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3
      with:
        jestArgs: test/services/AlarmService.test.js