name: run integration testing
on:
 push:
  branches: [main]
 pull_request:
  branches: [main, develop]
jobs: 
  integration-test: 
   runs-on : ubuntu-latest
   strategy: 
    matrix:
     node-version: [17.x]
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: andrea
          POSTGRES_PASSWORD: localPswd
          POSTGRES_DB: ocean_friend_bd
        ports:
          - 5432: 5432

